name: Build and push Docker image to Docker Hub
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

# When this workflow is in main or default branch, can use the 'workflow_run'
#  workflow_run:  # Dependency between workflows
#    workflows: ["CI Python"]
#    types: [completed]
#    branches:
#      - '*'

env:
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
  AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  push_to_registry:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Triggers only if dependent workflow is successful
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/sensorsapi

      - name: Login to Docker Hub
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sensorsapi:latest
